title: Live Essences
short_title: Live
subtitle: ""
description: "NOURISH | REVIVE | ENERGIZE. Transforming medicinal plants into wellness shots. Live Essences offer a selection of drinks, made from herbs, fruits and wild roots rich in natural vitamins, minerals, antioxidants and probiotics, for an healthy life."
keywords: natural, fruits, vitamins, minerals, antioxidants, botanical essences, probiotics, healthy life, Live Essences, herbs, wild roots
lang: en
version: 0.0.1
baseurl: ""
url: "https://liveessences.junglestar.org"
qr: true # 'true' or empty put qr.svg in includes/defs.html call it: icn--qr

company:
  name: Live Essences #
  legal_name: #if overrides 'company.name' in footer
  email: liveessences@gmail.com
  telephone:
  telephone_whatsapp: #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: "https://www.facebook.com/liveessences"
  youtube:
  instagram: "https://www.instagram.com/liveessences"
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics:
  verification:

# Build settings
markdown: kramdown
plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
 series:
  output: true
  permalink: /:title/
 years:
  output: true
  permalink: /:title/
 pages:
  output: true
  permalink: /:title/
 about:
  output: true
  permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: "painting"

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:
