title: Live Essences
short_title: Live Essences
subtitle: ""
description: "NOURISH, PROTECT, ENERGIZE. Medicinal plants made Wellness Shots. We make botanical drinks rich in vitamins, minerals, antioxidants, probiotics, to live healthy"
keywords: natural, fruits, vitamins, minerals, antioxidants, botanical, essences, probiotics, healthy life, Live Essences, herbs, wild roots, drinks, Bali, Indonesia, made in Bali.
lang: en
version: 0.2.9
baseurl: ""
url: "https://live-essences.com"
qr: true # 'true' or empty put qr.svg in includes/defs.html call it: icn--qr

company:
  name: Live Essences #
  legal_name: #if overrides 'company.name' in footer
  email: liveessences@gmail.com
  telephone:
  telephone_whatsapp: +628123858928 #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: "https://www.facebook.com/liveessences"
  youtube: "https://www.youtube.com/channel/UC-CrtGFNj_L4-7vbRtXzQQw/featured?disable_polymer=1"
  instagram: "https://www.instagram.com/liveessences"
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics: UA-122466061-1
  verification:

# Build settings
markdown: kramdown
plugins:
 - jekyll/tagging
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - gulpfile.js
  - package.json
  - package-lock.json
  - .DS_Store
  - Icon
  - node_modules
  - uploads
  - rakefile

permalink: /:title/ # pretty

collections:
 wellnessshots:
  output: true
  permalink: /wellnessshots/:title/
 pages:
  output: true
  permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: "product"

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:
