---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: _wellnessshots
  label: Wellnessshots
  create: all
  match: "**/*"
- type: directory
  path: _retailers
  label: Retailers
  create: none
  match: "**/*"
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: document
  path: index.md
  label: Homepage
- type: document
  path: _data/retailers.csv
  label: Retailers
  match: "**/*"
- type: document
  path: README.md
  label: Help
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
